spring:
  devtools:
    remote:
      restart:
        enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:dovalgaval
    username: sa
    password:
    driver-class-name: org.h2.Driver
  application:
    name: secret_auth
  config:
    import: vault://
  cloud:
    vault:
      uri: http://3.38.29.198:8200
      token: hvs.CAESIOcANYVUDhK_dgU1UHiwLQQviTWoxSU6Vj8U5UMHTOIHGh4KHGh2cy5YSW93Y0lkZFc1VkI5TnR5ajNtaUZXZVY
      kv:
        default-context: secret_auth
